### ISSUE TITLE
External Option / Method to check if tooltip is visible at the moment

### ISSUE THREAD

**Issue by gubagu** [vadikom/poshytip#10]
I was trying to to make Poshy work with jQuery Validation plugin and I couldn't find option or method to check whether element's tooltip is active or not. I wanted to use it with the onkeyup validation process of the jQuery Validation plugin. Is that correct ?

Thanks in advance,
Guby

**Comment by vadikom** [comment]
You can check like this:

<pre>var tipActive = $('#selector').data('poshytip').$tip.data('active');</pre>

**Comment by gubagu** [comment]
Thanks man you don't know it but you made my day.
I was going through the code but I got lost in the proxy. I guess I have much to learn.

Thanks man have a wonderful day !
