### ISSUE TITLE
Large popups rendering bug

### ISSUE THREAD

**Issue by yekver** [vadikom/poshytip#14]
Here is the bug while large popus is rendering (tooltip height should be > 750px)
This is css bug, I don't think that this is good idea to use large image files to draw popup inside the table. For css2 here should be a better way, and with css3 we can draw popups without images at all.

![bug1](https://f.cloud.github.com/assets/1935877/157475/d1499234-76c3-11e2-9f72-7b54a23b0777.PNG)
![bug2](https://f.cloud.github.com/assets/1935877/157476/d1653732-76c3-11e2-8cc9-4a4254fa7fca.PNG)

**Comment by vadikom** [comment]
This is a known limitation of the script, it's mentioned on the home page - "You need to create one big image for the tooltip body - e.g. something like 1024x768 pixels (which should be enough for anything you may want to display inside a tooltip in the browser viewport)."

Poshytip was actually created to allow using just a single background image to style the whole tooltip in varying sizes, so this is not an issue but the main idea behind the script.

As for CSS3 - there is nothing preventing you from using CSS3 to style the tooltip if you like - just don't set a background image in your CSS class for the tooltip (and then the script will not even generate the table structure around the tooltip content to draw the scalable image background) and you can use just CSS3 to style your tips.
