### ISSUE TITLE
compatibility in jquery

### ISSUE THREAD

**Issue by caoxudong** [vadikom/poshytip#17]
hi,

Thanks for your work, I love poshytip very much.

Now I use poshytip with jquery-1.9.1, but there's an error at jquery.poshytip.js:12 when loading poshytip.

```
Uncaught TypeError: Cannot read property 'msie' of undefined 
```

and the source code is:

```
ie6 = $.browser.msie && $.browser.version == 6;
```

I checked [jquery api](http://api.jquery.com/jQuery.browser/), which says

> Description: Contains flags for the useragent, read from navigator.userAgent. We recommend against using this property; please try to use feature detection instead (see jQuery.support). jQuery.browser may be moved to a plugin in a future release of jQuery.

and in its [upgrade-guide](http://jquery.com/upgrade-guide/1.9/#jquery-browser-removed), says

> The `jQuery.browser()` method has been deprecated since jQuery 1.3 and is removed in 1.9

So, I change the source code to 

```
ie6 = $.support.msie && $.support.version == 6;
```

then, it works.

**Comment by vadikom** [comment]
Yep, this is a known issue in v1.1 which is already fixed in the current code. So please just download directly from GitHub and it should work:

https://github.com/vadikom/poshytip/archive/master.zip

I will release v1.2 soon, just need to find some time for it...

**Comment by caoxudong** [comment]
ok£¬thanks

2013/4/22 Vasil Dinkov notifications@github.com
