### ISSUE TITLE
Reuse containers

### ISSUE THREAD

**Issue by webpepper** [vadikom/poshytip#22]
I have pages with a lot of tooltips, and recently I realized that poshytip generates a set of HTML nodes for _each_ tooltip instance. On a randomly picked page poshytip generated 20KB of HTML code. That's a lot, to say the least.

My question/suggestion is: why not reuse HTML nodes? At least for dynamic tooltips that simulate the default browser behavior (triggered by mouseover and mouseout).

Yes, there will be cases when multiple nodes are required (tooltips activated on click that remain open, for example) but I think there's room for improvement.

**Comment by vadikom** [comment]
Actually, when I wrote the script initially I thought about using a pool for the tooltip containers so we could create and reuse as few containers as possible (or at least one for each separate class). This was in fact the initial idea, however, as soon as I decided to include a dynamic content logic it brought many complications - e.g. it meant we would need to keep a cached copy of the content anyway even when the tooltips are hidden, emptying the containers is also a bit problematic when the content has jQuery data and events bound, etc. Also some other features mean data, events, etc. would need to be set/unset each time when a container is reused. In some advanced use scenarios (involving API usage, etc.) the fact that the tooltip container element is not available even when the tip is hidden or that the container might be different each time the tip is shown might also cause troubles.

So in the end all those complications I could think of back then made me go for the solution where each tip has a separate element that is always there for us if we need to interact with it.

BTW, it would require quite big parts of the script to be reworked if we would like to change this logic now so I guess this will not happen soon, if at all.
