### ISSUE TITLE
can't get value of e.pageX, under some situation

### ISSUE THREAD

**Issue by hilerchyn** [vadikom/poshytip#23]
such as title, check the below pic:

![out](https://f.cloud.github.com/assets/1203912/1408321/574ca8ac-3d80-11e3-88b9-fdd5f03efff7.gif)

while click the menu, will get data via AJAX to replace the all menus. after replacing, the value of e.pageX and e.pageY are 'undefined'.

<pre>
mousemove: function(e) {
            if (this.disabled)
                return true;
<b>
            this.eventX = e.pageX;        // undefined
            this.eventY = e.pageY;        // undefined</b>
            if (this.opts.followCursor && this.$tip.data('active')) {
                this.calcPos();
                this.$tip.css({left: this.pos.l, top: this.pos.t});
                if (this.pos.arrow)
                    this.$arrow[0].className = 'tip-arrow tip-arrow-' + this.pos.arrow;
            }
        },
</pre>

I temporarily solve this problem, as below:

<pre>
show: function() {
            if (this.disabled || this.$tip.data('active'))
                return;

            this.reset();
            this.update();

            // don't proceed if we didn't get any content in update() (e.g. the element has an empty title attribute)
            if (!this.content)
                return;
                        
<b>
                        if(this.eventX === undefined)    // fix code 
                            return;
</b>                        
            this.display();
            if (this.opts.timeOnScreen)
                this.hideDelayed(this.opts.timeOnScreen);
        },
</pre>

please check and confirm.

thanks for your great work!

**Comment by vadikom** [comment]
Hi,

Sorry for the delay! I just committed a fix for this. Please grab the latest code from Github and let me know if you still have any troubles.

Cheers!
