### ISSUE TITLE
scrolling does not move the tip along with the element

### ISSUE THREAD

**Issue by tekbird** [vadikom/poshytip#3]
Scenario: I have a tip displayed next to a text box and when I scroll the div containing the text box, the tip doesn't move along with it. It simply stays where it was originally shown. Re-sizing windows, however, moves the tip to the element's new position.

Any ideas how to fix this?

**Comment by meglio** [comment]
In my Google Chrome it does. In what browser do you experience problem?

**Comment by vadikom** [comment]
The tips are absolute positioned by default so they should move with the rest of the page when it is scrolled, not sure why it doesn't happen for you.
