### ISSUE TITLE
Testing in jQuery 1.8.0

### ISSUE THREAD

**Issue by jakejscott** [vadikom/poshytip#5]
Hi @vadikom,

I know you probably haven't tried upgrading the library to jQuery 1.8.0 so here is a heads up if you ever plan to.

The following line of code returns a jQuery wrapped object instead of the outer height as you would hope.
https://github.com/vadikom/poshytip/blob/master/src/jquery.poshytip.js#L227

I think the bug in jQuery is in here:
https://github.com/jquery/jquery/blob/master/src/dimensions.js#L16

It is returning a DOM element instead! So I guess you could check for that and use height() + margin + padding ?

**Comment by sislamoglu** [comment]
Actually poshytip not working at all with 1.8.0.. I'm expecting a 1.2 version soon like done with 1.7

**Comment by vadikom** [comment]
Thanks! I will try to check this soon..

**Comment by vadikom** [comment]
OK, I've checked 1.8.0 and 1.8.1 and couldn't notice any issue at all with all demos. Could you please give some example URL where I could see the issues? Also which browser do you use?

**Comment by sislamoglu** [comment]
Sorry mate, that was on my end. It seemed my old code that I have used using poshytip was borked by jQuery 1.8 and thought it was poshytip at first but not. Please forgive...  (but I'm not aware of the topic authors question)

**Comment by yhbyun** [comment]
http://stackoverflow.com/questions/12718084/jquery-1-8-2-noncurrent-jquery-ui-outerwidth-and-outerheight-broken

I modified the source and tooltip displayed as expected.

outerWidth() -> outerWidth(false)
outerHeight() -> outerHeight(false).
