### ISSUE TITLE
If tip contains table - display incorrect

### ISSUE THREAD

**Issue by vitalets** [vadikom/poshytip#7]
If there is table in content, plugin format it's width. It's because this line:
<code>var $table = this.$tip.find('table');</code>
It would be better to add specific css class to this fallback table and query by <code>table.classname</code> to exclude other tables.
Please, correct if possible, thx!

**Comment by vadikom** [comment]
Thanks very much! This is now fixed in the latest dev version. Sorry that it took a bit more time!
