### ISSUE TITLE
Poshytip showing on empty title

### ISSUE THREAD

**Issue by gubagu** [vadikom/poshytip#9]
Hi, first guys great tooltip plugin - easy to use, integrate and  has one of the most intelligent collision detection i've seen around for a tooltip. :+1: Last but not least big shout for Vasil Dinkov for the wonderful tutorial he has put together for all of us.
On the subject.
I trying to implement it to work nicely with a form generator to use it as more information about some fields. and i came across the following
Poshitip is showing even though the title attribute is empty.
Is that normal behavior or a bug ?

Thanks in advance,
Guby

**Comment by vadikom** [comment]
Thanks, glad you like the script! :)
Yeah, I guess you could call that a bug so I will add a fix for it as soon as I have some time to take a look..
In the meantime, this could be easily avoided with an attribute selector - e.g. like this:

<pre>$('#someElm[title!=""]').poshytip();</pre>

**Comment by vadikom** [comment]
This is fixed in v1.2.
